// <auto-generated />
using System;
using CryptoMarketAnalysis.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoMarketAnalysis.Infrastructure.Migrations
{
    [DbContext(typeof(CryptoMarketAnalysisDbContext))]
    partial class CryptoMarketAnalysisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoMarketAnalysis.Domain.Entities.CryptoAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasDatabaseName("ix_crypto_assets_symbol");

                    b.ToTable("crypto_assets", (string)null);
                });

            modelBuilder.Entity("CryptoMarketAnalysis.Domain.Entities.MarketDataPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal?>("MarketCapUsd")
                        .HasColumnType("numeric(28, 2)")
                        .HasColumnName("market_cap_usd");

                    b.Property<Guid>("MarketDataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_data_source_id");

                    b.Property<decimal>("PriceUsd")
                        .HasColumnType("numeric(28, 10)")
                        .HasColumnName("price_usd");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.Property<decimal?>("Volume24hUsd")
                        .HasColumnType("numeric(28, 2)")
                        .HasColumnName("volume_24h_usd");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "TimestampUtc")
                        .HasDatabaseName("ix_market_data_points_asset_id_timestamp_utc");

                    b.HasIndex("MarketDataSourceId", "TimestampUtc")
                        .HasDatabaseName("ix_market_data_points_market_data_source_id_timestamp_utc");

                    b.HasIndex("AssetId", "MarketDataSourceId", "TimestampUtc")
                        .IsUnique()
                        .HasDatabaseName("ux_market_data_points_asset_id_market_data_source_id_timestamp_utc");

                    b.ToTable("market_data_points", (string)null);
                });

            modelBuilder.Entity("CryptoMarketAnalysis.Domain.Entities.MarketDataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_market_data_sources_code");

                    b.ToTable("market_data_sources", (string)null);
                });

            modelBuilder.Entity("CryptoMarketAnalysis.Domain.Entities.MarketDataPoint", b =>
                {
                    b.HasOne("CryptoMarketAnalysis.Domain.Entities.CryptoAsset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CryptoMarketAnalysis.Domain.Entities.MarketDataSource", null)
                        .WithMany()
                        .HasForeignKey("MarketDataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
